# Generated by Django 3.0.3 on 2020-03-02 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True)),
                ('slug', models.SlugField(max_length=64)),
                ('description', models.TextField(max_length=2048)),
                ('add_timestamp', models.DateTimeField(auto_now=True)),
                ('done_timestamp', models.DateTimeField(blank=True)),
                ('is_done', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Todo item',
                'verbose_name_plural': 'Todo items',
                'ordering': ['-add_timestamp', '-is_done'],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('title', 'slug'), name='unique_title'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(check=models.Q(done_timestamp__lt=django.db.models.expressions.F('add_timestamp')), name='done_ts_verification'),
        ),
    ]
